# Generated by Django 5.0.1 on 2024-01-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_profile',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
