# Generated by Django 5.0.1 on 2024-01-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_person_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
